service: ksmcounseling-form-handler
provider:
  name: aws
  runtime: nodejs16.x
  profile: kyle
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "*"
  httpApi:
    cors: true

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  form:
    handler: handler.handler
    environment:
      EMAIL: "kristyn@fireflyplaytherapy.com"
    events:
      - httpApi:
          path: /form
          method: POST
